language: node_js

node_js:
 - "7"
 - "6"

cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules
    - jest-cache

install:
 - yarn install
 - cd example && yarn install
 - cd ..

script:
 - yarn run lint
 - yarn run flow
 - yarn test -- --cacheDirectory="jest-cache"
